defaults:
  - _self_
  - /data: openwebtext

seed: 1

loader:
  global_batch_size: 512
  eval_global_batch_size: 512
  # Note: batch_size and eval_batch_size are **per machine**
  batch_size: 128
  eval_batch_size: 128
  num_workers: 16
  pin_memory: True

eval:
  checkpoint_path: ''  # Used to evaluate a checkpoint after training.
  disable_ema: False
  n_steps: 128
  ode_method: heun2
